routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Route::get('/', ['as' => 'front.index', function () {
//     return view('front.index');
// }]);

//RUTAS DEL FRONTEND
// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [
	'as' => 'front.index',
	'uses' => 'FrontController@index'
	]);

Route::get('categories/{name}', [
	'uses' 	=> 'FrontController@searchCategory',
	'as' 	=> 'front.search.category'
	]);

Route::get('tags/{name}', [
	'uses' 	=> 'FrontController@searchTag',
	'as' 	=> 'front.search.tag'
	]);

Route::get('articles/{slug}', [
	'uses' => 'FrontController@viewArticle',
	'as' => 'front.view.article'
	]);


//RUTAS DEL PANEL DE ADMINISTRACIÓN
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function() {

	// Route::get('/', ['as' => 'admin.index', function () {
	// 	return view('welcome');
	// }]);

	Route::get('/', function () {
		return view('welcome');
	});

	Route::group(['middleware' => 'admin'], function() {
		
		Route::resource('users', 'UsersController');
		Route::get('users/{id}/destroy', [
			'uses' => 'UsersController@destroy', 
			'as' => 'admin.users.destroy'
			]);
	});

	Route::resource('categories', 'CategoriesController');
	Route::get('categories/{id}/destroy', [
		'uses' => 'CategoriesController@destroy', 
		'as' => 'admin.categories.destroy'
		]);

	Route::resource('tags', 'TagsController');
	Route::get('tags/{id}/destroy', [
		'uses' => 'TagsController@destroy', 
		'as' => 'admin.tags.destroy'
		]);

	Route::resource('articles', 'ArticlesController');
	Route::get('articles/{id}/destroy', [
		'uses' => 'ArticlesController@destroy', 
		'as' => 'admin.articles.destroy'
		]);

	Route::get('images', [
		'uses' => 'ImagesController@index',
		'as'   => 'images.index'
		]);

});
Auth::routes();

Route::get('/home', 'HomeController@index');

// Authentication routes...

// Route::get('admin/auth/login', [
// 	'uses' => 'Auth\LoginController@getLogin', 
// 	'as' => 'admin.auth.login'
// 	]);

// Route::post('admin/auth/login', [
// 	'uses' => 'Auth\LoginController@postLogin', 
// 	'as' => 'admin.auth.login'
// 	]);


// Route::get('admin/auth/logout', [
// 	'uses' => 'Auth\LoginController@getLogout', 
// 	'as' => 'admin.auth.logout'
// 	]);

resources/views/admin/template/partials/errors.blade.php
@if(count($errors) > 0)
	<div class="alert alert-danger" role="alert">
		<ul>
			@foreach($errors->all() as $error)
				<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
@endif

resources/views/admin/template/partials/nav.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">ECAPS</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      @if(Auth::user())
        <ul class="nav navbar-nav">
          <li><a href="{{ url('/admin') }}">Inicio</a></li>
          @if(Auth::user()->admin())
            <li><a href="{{ route('users.index') }}">Usuarios</a></li>
          @endif
          <li><a href="{{ route('categories.index') }}">Categorías</a></li>
          <li><a href="{{ route('articles.index') }}">Artículos</a></li>
          <li><a href="{{ route('images.index') }}">Imágenes</a></li>
          <li><a href="{{ route('tags.index') }}">Tags</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#">Página Principal</a></li>
          {{-- <li><a href="{{ route('front.index') }}" target="_blank">Página Principal</a></li> --}}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              {{ Auth::user()->name }}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <a href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Salir</a>
                  <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                  </form>
                {{-- {{ url('/logout') }} --}}
                {{-- {{ route('admin.auth.logout') }} --}}
              </li>
            </ul>
          </li>
        </ul>
        @else
          <ul class="nav navbar-nav">
            <li><a href="{{ url('/login') }}">Login</a></li>
          </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>